spring:
 datasource:
  generate-unique-name: false
  name: chickenCounter
  username: admin
  password: admin
  #password: chick3nC*
 data:
  rest:
   base-path: /data-api
rsa:
 private-key: classpath:certs/private.pem
 public-key: classpath:certs/public.pem 
   
chickenCount:
 master:
  password: admin*
 app: /
 
 
---
spring:
 profiles: dev
   
chickenCount:
 app: http://localhost:3000